//Deposit
export const GET_ALL_DEPOSIT = "GET_ALL_DEPOSIT";
export const GET_ALL_DEPOSITS_POINTS_BY_PERSON =
  "GET_ALL_DEPOSITS_POINTS_BY_PERSON";
export const GET_ALL_DEPOSITS_POINTS_BY_DATE =
  "GET_ALL_DEPOSITS_POINTS_BY_DATE";
export const GET_DEPOSIT_POINT = "GET_DEPOSIT_POINT";
//Withdraw
export const GET_ALL_WITHDRAWS = "GET_ALL_WITHDRAWS";
export const GET_ALL_WITHDRAWS_POINTS_BY_REASON =
  "GET_ALL_WITHDRAWS_POINTS_BY_REASON";
export const GET_ALL_WITHDRAWS_POINTS_BY_REASON_MAJOR =
  "GET_ALL_WITHDRAWS_POINTS_BY_REASON_MAJOR";
export const GET_WITHDRAW_POINT = "GET_WITHDRAW_POINT";

//Person
export const GET_ALL_PERSONS = "GET_ALL_PERSONS";

//Reason
export const GET_ALL_REASONS = "GET_ALL_REASONS";

//Dashboard
export const DASHBOARD_GET_ALL = "DASHBOARD_GET_ALL";

//Configuration
export const CONFIGURATION_FILES_GET_ALL = "CONFIGURATION_FILES_GET_ALL";